# Generated by Django 2.2 on 2022-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220316_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
